# Generated by Django 3.0.8 on 2020-07-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='branches',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='contacts',
            new_name='contact',
        ),
    ]
